// Loading screen tips
const loadingTips = [
    "fun fact: this site was built in a bedroom. literally.",
    "pro tip: the theme toggle is in the top right. you're welcome.",
    "did you know? there are way too many music projects listed here.",
    "loading... please don't refresh. i'm fragile.",
    "tip: hover over the title on the homepage for a surprise.",
    "remember: more reverb is always the answer.",
    "fun fact: Iron Gwazi is #1 and that's not up for debate.",
    "loading screens are just fancy waiting rooms.",
    "did you know? cables can never be too organized.",
    "pro tip: always label your ethernet cables. trust me.",
    "fun fact: shoegaze is just guitar + reverb + feelings.",
    "remember: there's no such thing as too much tape hiss.",
    "loading... this is taking longer than a theme park queue.",
    "did you know? VLANs are basically folders for your network.",
    "tip: the cookie banner won't judge your choice.",
    "fun fact: lo-fi is a vibe, not a limitation.",
    "remember: breakbeats make everything better.",
    "did you know? hyperpop is just organized chaos.",
    "pro tip: always use the Oxford comma.",
    "loading... calculating optimal cable management strategies.",
    "fun fact: this site has more projects than completed tasks.",
    "did you know? B&M coasters are butter smooth.",
    "tip: RMC conversions are basically magic.",
    "remember: theming > raw stats. fight me.",
    "fun fact: queue line music hits different at 2am.",
    "did you know? UniFi gear is addictive. send help.",
    "pro tip: rgb lighting makes servers 10% faster. probably.",
    "loading... applying unnecessary animations.",
    "remember: dark mode is superior. sorry not sorry.",
    "fun fact: the hamburger menu is named after food. wild.",
    "did you know? this loading screen is exactly 1.6 seconds.",
    "tip: gradient text is peak web design. don't @ me.",
    "remember: backdrop blur makes everything fancy.",
    "fun fact: border-radius: 980px is basically a circle.",
    "did you know? flex-wrap: wrap saves lives.",
    "pro tip: z-index: 9999 is a cry for help.",
    "loading... pretending to do important computer things.",
    "remember: !important is usually not important.",
    "fun fact: this tip system has exactly 50 tips.",
    "did you know? css variables are criminally underrated.",
    "tip: transition: all is lazy but effective.",
    "remember: mobile-first design is the way.",
    "fun fact: this site uses way too many css animations.",
    "did you know? aria labels make the web accessible. use them.",
    "pro tip: semantic html is your friend.",
    "loading... sacrificing performance for aesthetics.",
    "remember: user experience > developer convenience.",
    "fun fact: the loading bar is just vibing.",
    "did you know? there are 10desires and they're all coasters.",
    "tip: refresh the page to see a different loading tip!"
];
